# Site data

header-logo: /img/anagrams-logo.png
header-text: Real life anagrams podcast
header-sub-text: with Astrid Chug and Stephanie Sol



footer-text: Real Life Anagrams
footer-subtext: is a podcast on women empowerment wherein we make STEM relatable and discuss being a woman in the Fourth Industrial Revolution. It is hosted by Astrid Chug - Software Engineer and Entrepreneur, and Stephanie Sol - Actress, Model, and Entrepreneur.

